//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedItem
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public decimal Price { get; set; }
        public int Qauntity { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
